### PR TITLE
Ignore blank lines preceding actual code input in E mode.

### LINKED ISSUE #1: Allow multiple lines for 'E' input
Allow the user to enter multiple lines when **E**xecuting code - [TODO link](https://github.com/danstewart/BFI/blob/c31465f622d12d44f549280ee65ae06305cd603f/bf.pl#L62)

### PR DESCRIPTION
**Pull request by richardleach**
This pull request attempts to fix #1 and the associated TODO comment. Hopefully it's the behaviour you had in mind?

### CODE REVIEW

**Comment by danstewart** [comment]
@richardleach Thanks for the PR. 

What I meant was to allow entering multiple lines before processing the input, if you add the `TODO` comment back in I'll merge this as it's still a good change to add in.

Cheers

**Comment by danstewart** [comment]
Thanks!

**Comment by richardleach** [comment]
Cheers. :-)  If allowing multiple lines of entry, what condition would signify that the user had finished entry and it was time to process? (e.g. empty line once there had been a valid line of input, a 'q' character as part of an input line, an isolated 'q' on a line by itself, other?)

**Comment by danstewart** [comment]
Yeah, that's what I was thinking, it would allow you to add line breaks between the code but pressing enter on a blank line would actually execute it.

**Pull request merged**
